### ISSUE TITLE
Configure Flipper as a default debugger for mobile device

### ISSUE THREAD

**Issue by kmezynski** [chudoklates/light-sensor-app#8]

**Comment by chudoklates** [comment]
Since the release of Expo SDK 41, `react-native-reanimated` v2, which is used in a lot of places in our modules causes the native debug mode to crash.

In order to solve this, we chose Flipper as our default tool for debugging the app

Follow the instructions [here](https://fbflipper.com/docs/getting-started/index) to install Flipper

Once installed, simply run the application as normal, and connect to it from the Flipper GUI
